/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[];

export type DkRegion =
  "Hovedstaden" | "Midtjylland" | "Nordjylland" | "Sjælland" | "Syddanmark";

export type FundingTheme =
  | "green"
  | "international"
  | "local_community"
  | "social"
  | "student"
  | "youth";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<number, number | string, number | string>;

export type ReviewStatus = "dismissed" | "generated" | "overridden";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Api {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
}

export interface FundingCall {
  amounts_kr: Generated<number[]>;
  completeness: Numeric | null;
  confidence: Generated<string | null>;
  content_hash: string;
  created_at: Generated<Timestamp>;
  deadline_type: Generated<string>;
  description: string | null;
  eligibility: string | null;
  funder_type: string | null;
  funding_body: string | null;
  id: Generated<number>;
  last_checked: Timestamp | null;
  level: string | null;
  missing_fields: Generated<string[]>;
  municipality: string | null;
  ngo_eligible: boolean | null;
  record_kind: Generated<string>;
  region: DkRegion | null;
  source: string;
  source_url: string;
  status: Generated<string>;
  summary: string | null;
  themes: Generated<ArrayType<FundingTheme>>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface FundingRound {
  call_id: number;
  deadline_date: Timestamp | null;
  decision_date: Timestamp | null;
  expected_next_open_date: Timestamp | null;
  id: Generated<number>;
  open_date: Timestamp | null;
  round_no: number | null;
}

export interface FundingSource {
  active: Generated<boolean>;
  base_url: string | null;
  created_at: Generated<Timestamp>;
  key: string;
  last_checked: Timestamp | null;
  name: string;
  source_type: string | null;
}

export interface MatchReason {
  id: Generated<number>;
  kind: string;
  match_id: number;
  message: string;
  rule_key: string;
  weight: Generated<number>;
}

export interface MatchResult {
  admin_note: string | null;
  call_id: number;
  created_at: Generated<Timestamp>;
  fit_label: string;
  id: Generated<number>;
  manual_fit_label: string | null;
  manual_score: number | null;
  review_status: Generated<ReviewStatus>;
  score: number;
}

export interface OrgProfile {
  country: string;
  created_at: Timestamp;
  established_year: number | null;
  has_facilities: boolean;
  id: number;
  legal_status: string;
  municipality: string;
  name: string;
  region: DkRegion;
  staff_count: number;
  target_groups: string[];
  themes: ArrayType<FundingTheme>;
  updated_at: Timestamp;
  updated_by: string | null;
}

export interface DB {
  api: Api;
  funding_call: FundingCall;
  funding_round: FundingRound;
  funding_source: FundingSource;
  match_reason: MatchReason;
  match_result: MatchResult;
  org_profile: OrgProfile;
}
