/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CallStatus = "closed" | "open" | "unknown" | "upcoming";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<number, number | string, number | string>;

export type ReviewStatus = "dismissed" | "generated" | "overridden";

export type TagType = "country" | "other" | "sector" | "target_group" | "theme";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Api {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
}

export interface FundingCall {
  budget_max: Numeric | null;
  budget_min: Numeric | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  description: string | null;
  eligibility: string | null;
  external_id: string | null;
  funder_type: string | null;
  funding_body: string | null;
  funding_source_id: number;
  id: Generated<number>;
  level: string | null;
  ngo_eligible: boolean | null;
  recurring: Generated<boolean>;
  source_url: string | null;
  status: Generated<CallStatus>;
  summary: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface FundingCallTag {
  call_id: number;
  tag_id: number;
}

export interface FundingRound {
  call_id: number;
  deadline_date: string | null;
  decision_date: string | null;
  expected_next_open_date: string | null;
  id: Generated<number>;
  open_date: string | null;
  round_no: number | null;
}

export interface FundingSource {
  active: Generated<boolean>;
  base_url: string | null;
  id: Generated<number>;
  last_checked: Timestamp | null;
  name: string;
  source_type: string | null;
}

export interface MatchReason {
  id: Generated<number>;
  kind: string;
  match_id: number;
  message: string;
  weight: Generated<number>;
}

export interface MatchResult {
  admin_note: string | null;
  call_id: number;
  created_at: Generated<Timestamp>;
  fit_label: string;
  id: Generated<number>;
  manual_score: number | null;
  org_profile_id: Generated<number>;
  review_status: Generated<ReviewStatus>;
  score: number;
  updated_at: Generated<Timestamp>;
}

export interface Notification {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  match_id: number;
  message: string;
  read: Generated<boolean>;
}

export interface OrgProfile {
  admin_capacity: string | null;
  city: string;
  country: string;
  id: number;
  legal_status: string;
  name: string;
  staff_count: number;
}

export interface OrgProfileTag {
  org_profile_id: number;
  tag_id: number;
}

export interface Tag {
  id: Generated<number>;
  label: string;
  type: TagType;
}

export interface DB {
  api: Api;
  funding_call: FundingCall;
  funding_call_tag: FundingCallTag;
  funding_round: FundingRound;
  funding_source: FundingSource;
  match_reason: MatchReason;
  match_result: MatchResult;
  notification: Notification;
  org_profile: OrgProfile;
  org_profile_tag: OrgProfileTag;
  tag: Tag;
}
